# Generated by Django 5.0.7 on 2024-09-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='BillBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.IntegerField(db_index=True, unique=True)),
                ('total_bills', models.IntegerField(default=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_size', models.CharField(choices=[('50', '50g'), ('100', '100g'), ('200', '200g'), ('250', '250g'), ('500', '500g'), ('1000', '1kg'), ('2000', '2kg')], max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='management.itembase')),
            ],
        ),
    ]
