# Generated by Django 5.0.7 on 2024-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_billbook_options_dailyreadyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='stop_taking_order',
            field=models.BooleanField(default=False),
        ),
    ]
