# Generated by Django 5.0.7 on 2024-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_itembase_stop_taking_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreadyitem',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='itembase',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='userdeposits',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='itembase',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
