# Generated by Django 5.0.7 on 2024-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_dailyreadyitem_options_alter_itembase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='box_size',
            field=models.CharField(help_text='Box size in grams i.e. for 500gms, enter 500, for 1kg, enter 1000.', max_length=20),
        ),
    ]
