# Generated by Django 5.0.7 on 2024-10-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_order_payment_deposited_by_customer'),
        ('management', '0007_alter_item_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeposits',
            name='is_deposited_by_dealer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdeposits',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.order'),
        ),
        migrations.AddField(
            model_name='userdeposits',
            name='payment_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
    ]
