# Generated by Django 5.0.7 on 2024-10-24 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_userdeposits_is_deposited_by_dealer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeposits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdeposits',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
