# Generated by Django 5.0.7 on 2024-10-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_userdeposits_created_at_userdeposits_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreadyitem',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
