# Generated by Django 5.0.7 on 2024-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_dailyreadyitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreadyitem',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
