# Generated by Django 5.0.7 on 2024-09-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['bill_number']},
        ),
    ]
