# Generated by Django 5.0.7 on 2024-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deposited_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
